// <auto-generated />
using System;
using MCRental_Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCRental_Persistence.Migrations
{
    [DbContext(typeof(MCRentalDBContext))]
    partial class MCRentalDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MCRental_Models.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Beschikbaar")
                        .HasColumnType("bit");

                    b.Property<double>("DagPrijs")
                        .HasColumnType("float");

                    b.Property<int>("FiliaalId")
                        .HasColumnType("int");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nummerplaat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FiliaalId");

                    b.ToTable("Autos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschikbaar = true,
                            DagPrijs = 70.0,
                            FiliaalId = 1,
                            Merk = "Toyota",
                            Model = "Corolla",
                            Nummerplaat = "1-ABC-123",
                            type = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Beschikbaar = true,
                            DagPrijs = 65.0,
                            FiliaalId = 2,
                            Merk = "Ford",
                            Model = "Focus",
                            Nummerplaat = "1-DEF-456",
                            type = "Hatchback"
                        },
                        new
                        {
                            Id = 3,
                            Beschikbaar = false,
                            DagPrijs = 95.0,
                            FiliaalId = 3,
                            Merk = "BMW",
                            Model = "X3",
                            Nummerplaat = "1-GHI-789",
                            type = "SUV"
                        },
                        new
                        {
                            Id = 4,
                            Beschikbaar = true,
                            DagPrijs = 90.0,
                            FiliaalId = 1,
                            Merk = "Audi",
                            Model = "A4",
                            Nummerplaat = "1-JKL-012",
                            type = "Sedan"
                        },
                        new
                        {
                            Id = 5,
                            Beschikbaar = true,
                            DagPrijs = 75.0,
                            FiliaalId = 2,
                            Merk = "Volkswagen",
                            Model = "Golf",
                            Nummerplaat = "1-MNO-345",
                            type = "Hatchback"
                        },
                        new
                        {
                            Id = 6,
                            Beschikbaar = false,
                            DagPrijs = 100.0,
                            FiliaalId = 3,
                            Merk = "Mercedes",
                            Model = "GLC",
                            Nummerplaat = "1-PQR-678",
                            type = "SUV"
                        });
                });

            modelBuilder.Entity("MCRental_Models.Filiaal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StadId")
                        .HasColumnType("int");

                    b.Property<string>("Telefoon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StadId");

                    b.ToTable("Filialen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adres = "Kerkstraat 1",
                            Email = "info.antwerpen@mcrental.be",
                            Naam = "Filiaal Antwerpen",
                            StadId = 2,
                            Telefoon = "03 123 45 67"
                        },
                        new
                        {
                            Id = 2,
                            Adres = "Grote Markt 1",
                            Email = "info.brussel@mcrental.be",
                            Naam = "Filiaal Brussel",
                            StadId = 1,
                            Telefoon = "02 123 45 67"
                        },
                        new
                        {
                            Id = 3,
                            Adres = "Bondgenotenlaan 1",
                            Email = "info.leuven@mcrental.be",
                            Naam = "Filiaal Leuven",
                            StadId = 3,
                            Telefoon = "016 123 45 67"
                        });
                });

            modelBuilder.Entity("MCRental_Models.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeboorteDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("StadId")
                        .HasColumnType("int");

                    b.Property<string>("Telefoon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StadId");

                    b.ToTable("Klanten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Achternaam = "Janssens",
                            Adres = "Kerkstraat 10",
                            Email = "jan.janssens@hotmail.com",
                            GeboorteDatum = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StadId = 2,
                            Telefoon = "0470 123 456",
                            Voornaam = "Jan"
                        },
                        new
                        {
                            Id = 2,
                            Achternaam = "Pieters",
                            Adres = "Markt 5",
                            Email = "piet.pieters@hotmail.com",
                            GeboorteDatum = new DateTime(1990, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StadId = 1,
                            Telefoon = "0471 654 321",
                            Voornaam = "Piet"
                        },
                        new
                        {
                            Id = 3,
                            Achternaam = "Klaassen",
                            Adres = "Bondgenotenlaan 3",
                            Email = "klaas.klaassen@hotmail.com",
                            GeboorteDatum = new DateTime(1978, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StadId = 3,
                            Telefoon = "0472 789 012",
                            Voornaam = "Klaas"
                        });
                });

            modelBuilder.Entity("MCRental_Models.Reservatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EindDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AutoId");

                    b.HasIndex("KlantId");

                    b.ToTable("Reservaties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoId = 2,
                            EindDatum = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KlantId = 1,
                            StartDatum = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AutoId = 1,
                            EindDatum = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KlantId = 2,
                            StartDatum = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AutoId = 5,
                            EindDatum = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KlantId = 3,
                            StartDatum = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MCRental_Models.Stad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Steden");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Brussel",
                            Postcode = "1000"
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Antwerpen",
                            Postcode = "2000"
                        },
                        new
                        {
                            Id = 3,
                            Naam = "Leuven",
                            Postcode = "3000"
                        },
                        new
                        {
                            Id = 4,
                            Naam = "Luik",
                            Postcode = "4000"
                        },
                        new
                        {
                            Id = 5,
                            Naam = "Namen",
                            Postcode = "5000"
                        },
                        new
                        {
                            Id = 6,
                            Naam = "Charleroi",
                            Postcode = "6000"
                        },
                        new
                        {
                            Id = 7,
                            Naam = "Bergen",
                            Postcode = "7000"
                        },
                        new
                        {
                            Id = 8,
                            Naam = "Brugge",
                            Postcode = "8000"
                        },
                        new
                        {
                            Id = 9,
                            Naam = "Gent",
                            Postcode = "9000"
                        });
                });

            modelBuilder.Entity("MCRental_Models.Auto", b =>
                {
                    b.HasOne("MCRental_Models.Filiaal", "Filiaal")
                        .WithMany("Autos")
                        .HasForeignKey("FiliaalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiaal");
                });

            modelBuilder.Entity("MCRental_Models.Filiaal", b =>
                {
                    b.HasOne("MCRental_Models.Stad", "Stad")
                        .WithMany("Filialen")
                        .HasForeignKey("StadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stad");
                });

            modelBuilder.Entity("MCRental_Models.Klant", b =>
                {
                    b.HasOne("MCRental_Models.Stad", "Stad")
                        .WithMany("Klanten")
                        .HasForeignKey("StadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stad");
                });

            modelBuilder.Entity("MCRental_Models.Reservatie", b =>
                {
                    b.HasOne("MCRental_Models.Auto", "Auto")
                        .WithMany("Reservaties")
                        .HasForeignKey("AutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCRental_Models.Klant", "Klant")
                        .WithMany("Reservaties")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auto");

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("MCRental_Models.Auto", b =>
                {
                    b.Navigation("Reservaties");
                });

            modelBuilder.Entity("MCRental_Models.Filiaal", b =>
                {
                    b.Navigation("Autos");
                });

            modelBuilder.Entity("MCRental_Models.Klant", b =>
                {
                    b.Navigation("Reservaties");
                });

            modelBuilder.Entity("MCRental_Models.Stad", b =>
                {
                    b.Navigation("Filialen");

                    b.Navigation("Klanten");
                });
#pragma warning restore 612, 618
        }
    }
}
